version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule: 
      interval: "daily"
      time: "23:28"
      timezone: "America/New_York"
    labels:
      - "nuget-dependencies"
  - package-ecosystem: "docker"
    directory: "/"
    schedule: 
      interval: "daily"
      time: "23:40"
      timezone: "America/New_York"
    labels:
      - "docker-dependencies"