version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule: 
      interval: "daily"
      time: "23:23"
      timezone: "America/New_York"
    labels:
      - "nuget-dependencies"