name: Continuous Integration
on:
  push:
  #   branches:
  #     - 'main'
  #     - 'dev'
    tags:
        - 'v*.*.*'
  # pull_request:
  #   branches:
  #     - 'main'
  #     - 'dev'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      working-directory: ./AISmartHomeApp/
      run: dotnet restore
    - name: Build
      working-directory: ./AISmartHomeApp/
      run: dotnet build --no-restore
  docker:
    name:  Docker Build & Push
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
    - name: Checkout
      uses: actions/checkout@v3  
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Image
      working-directory: ./AISmartHomeApp/
      run: dotnet publish -c Release -p:ContainerImageName=${{ secrets.DOCKER_USERNAME }}/aismarthome
    - name: Push Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/aismarthome --all-tags