# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  push:
  #   branches:
  #     - 'main'
  #     - 'dev'
    tags:
        - 'v*.*.*'
  # pull_request:
  #   branches:
  #     - 'main'
  #     - 'dev'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '45 04 * * *' # every day at 00:30
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: csharp/global.json
      # https://github.com/docker/setup-buildx-action
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker meta
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: |
              markgreenway/aismarthome
            tags: |
              type=ref,event=branch
              type=ref,event=pr
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}


      - name: Publish and push the container image
        run: |
          dotnet publish -t:PublishContainer -p ContainerImageTag=${{ steps.meta.outputs.labels }} --arch arm64 -p ContainerPlatform=linux/arm64 -p ContainerRegistry=docker.io



      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: markgreenway/aismarthome       